apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: parking-manager-frontend-deployment
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: parking-manager
    spec:
      containers:
      - name: parking-manager-frontend-container
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m