apiVersion: v1
kind: Service
metadata:
  name: parking-manager-frontend-service
spec:
  type: LoadBalancer
  loadBalancerIP: "34.74.5.151"
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: parking-manager-frontend